wutsi:
  application:
    gateway-url: https://wutsi-gateway-prod.herokuapp.com
    server-url: ${wutsi.application.gateway-url}/shell
    asset-url: https://prod-wutsi.s3.amazonaws.com/static/wutsi-web
  platform:
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
        ttl: 86400
    storage:
      type: aws
      aws:
        bucket: int-wutsi
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
