spring:
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        debug: false

wutsi:
  application:
    env: prod
    server-url: ${wutsi.application.shell-url}
    asset-url: https://prod-wutsi.s3.amazonaws.com/static/wutsi-web
  platform:
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
        ttl: 86400
    security:
      api-key: ${API_KEY}
      verify-token: true
      token-blacklist:
        type: redis
        redis:
          url: ${REDIS_URL}
    storage:
      type: aws
      aws:
        bucket: int-wutsi
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
