spring:
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        debug: true

wutsi:
  application:
    env: test
    server-url: ${wutsi.application.shell-url}
  platform:
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
        ttl: 86400
    security:
      api-key: ${API_KEY}
    storage:
      type: aws
      aws:
        bucket: int-wutsi
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
