server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,health,info,scheduledtasks,mappings"

spring:
  main:
    lazy-initialization: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null

wutsi:
  application:
    env: test
    name: wutsi-shell-bff
    asset-url: https://int-wutsi.s3.amazonaws.com/static/wutsi-shell-bff
    server-url: http://localhost:${server.port}
    store-url: ${wutsi.application.server-url}
    shell-url: ${wutsi.application.server-url}
    cash-url: ${wutsi.application.server-url}
    login-url: ${wutsi.application.server-url}
    chat-url: https://wutsi-chat-bff-${wutsi.application.env}.herokuapp.com
    news-url: https://wutsi-news-bff-${wutsi.application.env}.herokuapp.com
    webapp-url: https://wutsi-web-test.herokuapp.com
  platform:
    cache:
      name: ${wutsi.application.name}
      type: local
    image:
      type: none
    messaging:
      url-shortener:
        type: none
    security:
      type: jwt
      api-key: "d779ed54-dadf-11ec-94e8-127037cd15a7"
      verify-token: false
      token-blacklist:
        type: none
      public-endpoints:
        - "POST /login"
        - "POST /login/**"
        - "POST /onboard"
        - "POST /onboard/**"
        - "GET /legacy-endpoints--"
        - "GET /qr-code/**"
        - "POST /shell/track/**"
        - "POST /firebase/on-message/**"
        - "POST /phone"
        - "POST /commands/login"
        - "POST /pages/city"
        - "POST /pages/confirm-pin"
        - "POST /pages/final"
        - "POST /pages/phone"
        - "POST /pages/pin"
        - "POST /pages/profile"
        - "POST /pages/verification"
        - "POST /commands/confirm-login-pin"
        - "POST /commands/save-profile"
        - "POST /commands/save-pin"
        - "POST /commands/create-wallet"
        - "POST /commands/verify-code"
        - "POST /commands/send-code"
        - "POST /commands/resend-code"
        - "POST /commands/save-city"
        - "POST /commands/login"
    tracing:
      client-id: ${wutsi.application.name}
    stream:
      name: ${wutsi.application.name}
      type: local
    storage:
      type: local

  store:
    pictures:
      max-per-product: 5
      max-width: 512
      max-height: 512

logging:
  level:
    root: INFO
    com:
      wutsi:
        platform:
          account:
            WutsiAccountApi: DEBUG
          contact:
            WutsiContactApi: DEBUG
          payment:
            WutsiPaymentApi: DEBUG
          sms:
            WutsiSmsApi: DEBUG
          tenant:
            WutsiTenantApi: DEBUG
  pattern:
    console: "%d type=%level logger=%class{20} thread=%thread %m%n"
    file: "%d type=%level logger=%class{20} thread=%thread %m%n"


