wutsi:
  application:
    server-url: https://wutsi-home-bff-prod.herokuapp.com
  platform:
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
        ttl: 86400
  toggles:
    send-sms-code: true
    verify-sms-code: true
