server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 512

management:
  endpoint:
    health:
      show-details: always
    info:
      git:
        mode: full
  endpoints:
    web:
      exposure:
        include: "beans,health,info,scheduledtasks,mappings"

spring:
  main:
    lazy-initialization: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
    default-property-inclusion: non_null

  mail:
    default-encoding: UTF-8
    host: localhost
    port: 2525
    username: username
    password: secret
    properties:
      mail:
        debug: true
        smtp:
          from: no-reply@wutsi.com
          auth: true
          starttls:
            enable: true
    test-connection: false

wutsi:
  application:
    env: test
    name: wutsi-shell-bff
    server-url: http://localhost:${server.port}
    cash-url: https://wutsi-cash-bff-${wutsi.application.env}.herokuapp.com
    chat-url: https://wutsi-chat-bff-${wutsi.application.env}.herokuapp.com
    login-url: https://wutsi-login-bff-${wutsi.application.env}.herokuapp.com
    news-url: https://wutsi-news-bff-${wutsi.application.env}.herokuapp.com
    shell-url: https://wutsi-shell-bff-${wutsi.application.env}.herokuapp.com
    store-url: https://wutsi-store-bff-${wutsi.application.env}.herokuapp.com
    asset-url: https://int-wutsi.s3.amazonaws.com/static/wutsi-web
  platform:
    cache:
      name: ${wutsi.application.name}
      type: local
    security:
      type: jwt
      api-key: "d779ed54-dadf-11ec-94e8-127037cd15a7"
      verify-token: false
      token-blacklist:
        type: none
      public-endpoints:
        - "GET /qr-code/**"
        - "POST /shell/track/**"
        - "POST /firebase/on-message/**"
    tracing:
      client-id: ${wutsi.application.name}
    stream:
      name: ${wutsi.application.name}
      type: local
      subscriptions:
        - wutsi-tenant
        - wutsi-account
    storage:
      type: local

logging:
  level:
    root: INFO
    com:
      wutsi:
        platform:
          account:
            WutsiAccountApi: DEBUG
          contact:
            WutsiContactApi: DEBUG
          payment:
            WutsiPaymentApi: DEBUG
          sms:
            WutsiSmsApi: DEBUG
          tenant:
            WutsiTenantApi: DEBUG
  pattern:
    console: "%d type=%level logger=%class{20} thread=%thread %m%n"
    file: "%d type=%level logger=%class{20} thread=%thread %m%n"


